### PR TITLE
fix for the redis password not being set in the connection string

### PR DESCRIPTION
**Pull request by rebrowning**
I'd like some feedback on how we want to handle this.

There are other options with how to configure redis in the underlying bitnami chart (generated password, secretfile). However I don't know how to grab either the generated helm value or the value from the secret file to then inject it into the redis url. Are there some additional coordination parameters we can use in st2 to set the password or an environment variable that st2 will consume for the redis password?

Additionally, you can set sentinel to be protected by the same password as well, however this `DOES NOT` work due to the tooz driver not populating the password for the sentinel client, only for the redis client that gets created from the sentinel get master request.

### CODE REVIEW

**Review by cognifloyd — APPROVED** [review]
I don't use the subchart, so I can't say which method will be better to use here. From reading, this looks good to me, but I'd prefer someone else who uses the redis subchart chime in before I merge this.

**Comment by arms11** [comment]
Hi @rebrowning I am one of the users who uses the sub-chart. As long as you have tested the deployment without password and it works, I think it's a good change. We want to make sure it's backward compatible. Could you please confirm?

**Comment by robertorch** [comment]
@arms11 I tested both with and without a password configuration for Redis when doing this. I'm more than happy to provide a couple screenshots after hours of the config/template/deployment success for completeness.

**Comment by arms11** [comment]
Nope. I appreciate the response.

**Comment by cognifloyd** [comment]
Please also add a changelog entry.

**Pull request merged**
